export const DATA_SERVICE_CATALOGS_REQUESTED =
  'DATA_SERVICE_CATALOGS_REQUESTED' as const;
export const DATA_SERVICE_CATALOGS_SUCCEEDED =
  'DATA_SERVICE_CATALOGS_SUCCEEDED' as const;
export const DATA_SERVICE_CATALOGS_FAILED =
  'DATA_SERVICE_CATALOGS_FAILED' as const;
