import { validateEnv } from "./utils/common";


const SKE_THEME_PROFILE =  process.env.NEXT_PUBLIC_SKE_THEME_PROFILE!;
const FDK_REGISTRATION_BASE_URI =  process.env.NEXT_PUBLIC_FDK_REGISTRATION_BASE_URI!;
const NAMESPACE =  process.env.NEXT_PUBLIC_NAMESPACE!;
const FDK_BASE_URI =  process.env.NEXT_PUBLIC_FDK_BASE_URI!;
const SSO_HOST =  process.env.NEXT_PUBLIC_SSO_HOST!;
const ADMIN_GUI_BASE_URI =  process.env.NEXT_PUBLIC_ADMIN_GUI_BASE_URI!;
const DATASERVICE_CATALOG_BASE_URI =  process.env.NEXT_PUBLIC_DATASERVICE_CATALOG_BASE_URI!;
const CONCEPT_REGISTRATION_HOST =  process.env.NEXT_PUBLIC_CONCEPT_REGISTRATION_HOST!;
const CONCEPT_CATALOG_BASE_URI =  process.env.NEXT_PUBLIC_CONCEPT_CATALOG_BASE_URI!;
const DATASET_CATALOG_BASE_URI =  process.env.NEXT_PUBLIC_DATASET_CATALOG_BASE_URI!;
const RECORDS_OF_PROCESSING_ACTIVITIES_BASE_URI =  process.env.NEXT_PUBLIC_RECORDS_OF_PROCESSING_ACTIVITIES_BASE_URI!;
const FDK_COMMUNITY_BASE_URI =  process.env.NEXT_PUBLIC_FDK_COMMUNITY_BASE_URI!;
const FDK_CMS_BASE_URI =  process.env.NEXT_PUBLIC_FDK_CMS_BASE_URI!;
const USE_DEMO_LOGO =  Boolean(process.env.NEXT_PUBLIC_USE_DEMO_LOGO!);

const env = {
  NAMESPACE,
  FDK_BASE_URI,
  SSO_HOST,
  SKE_THEME_PROFILE,
  FDK_REGISTRATION_BASE_URI,
  ADMIN_GUI_BASE_URI,
  DATASERVICE_CATALOG_BASE_URI,
  CONCEPT_REGISTRATION_HOST,
  CONCEPT_CATALOG_BASE_URI,
  DATASET_CATALOG_BASE_URI,
  RECORDS_OF_PROCESSING_ACTIVITIES_BASE_URI,
  FDK_COMMUNITY_BASE_URI,
  FDK_CMS_BASE_URI,
  USE_DEMO_LOGO,
  };


export default validateEnv(env);
