---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment-registration-portal.yaml
  - service-registration-portal.yaml
images:
  - name: registration-portal
    newName: eu.gcr.io/digdir-fdk-infra/registration-portal
    newTag: $(GIT_COMMIT_SHA)
