---
apiVersion: v1
kind: Service
metadata:
  name: registration-portal
spec:
  selector:
    app: registration-portal
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
