export const RECORD_COUNTS_REQUESTED = 'RECORD_COUNTS_REQUESTED' as const;
export const RECORD_COUNTS_SUCCEEDED = 'RECORD_COUNTS_SUCCEEDED' as const;
export const RECORD_COUNTS_FAILED = 'RECORD_COUNTS_FAILED' as const;
