export const LIST_CATALOGS_REQUESTED = 'LIST_CATALOGS_REQUESTED' as const;
export const LIST_CATALOGS_SUCCEEDED = 'LIST_CATALOGS_SUCCEEDED' as const;
export const LIST_CATALOGS_FAILED = 'LIST_CATALOGS_FAILED' as const;
