export const CONCEPT_CATALOGS_REQUESTED = 'CONCEPT_CATALOGS_REQUESTED' as const;
export const CONCEPT_CATALOGS_SUCCEEDED = 'CONCEPT_CATALOGS_SUCCEEDED' as const;
export const CONCEPT_CATALOGS_FAILED = 'CONCEPT_CATALOGS_FAILED' as const;
