export const SERVICE_CATALOGS_REQUESTED = 'SERVICE_CATALOGS_REQUESTED' as const;
export const SERVICE_CATALOGS_SUCCEEDED = 'SERVICE_CATALOGS_SUCCEEDED' as const;
export const SERVICE_CATALOGS_FAILED = 'SERVICE_CATALOGS_FAILED' as const;
